/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119811-gd4556c98f0-20250603"
#endif /* AVUTIL_FFVERSION_H */
